### ISSUE TITLE
Promoting Good Software

### ISSUE THREAD

**Issue by alexhallam** [mavelli/rocker-bayesian#1]
This is really great work; a big time saver for me and maybe many others. You should consider linking to this repo on [Stan Forums](http://discourse.mc-stan.org/). This may be a good way to get more users and have a community test this image.

Thanks again for putting this together!

**Comment by mavelli** [comment]
agreed! i will check the rebuilding (yesterday night i forgot to quote the "repo" argument from INLA installation) and when i use the new image for myself, i will announce it, thanx
