### ISSUE TITLE
brms not installed

### ISSUE THREAD

**Issue by alexhallam** [mavelli/rocker-bayesian#2]
While in the server I type

`> library(brms)`

and get the error

>Error in library(brms) : there is no package called ‘brms’

**Comment by mavelli** [comment]
I know. It seems yesterday evening it failed building on docker hub.
I fixed the missing quotes for —repo argument in install2.r this morning
but not sure when the next image will be ready.
The building takes hours. Check on docker hub under „build details“ of
rocker-bayesian when it is successfully finished.

Alex Hallam <notifications@github.com> schrieb am Do. 5. Juli 2018 um 12:49:

**Comment by mavelli** [comment]
fixed the mistakes i introduced yesterday night in the "cleanup" attempt - should build fine now also on docker hub and be ready in some hours

**Comment by alexhallam** [comment]
What do these errors mean on the rocker-baysian [docker hub](https://hub.docker.com/r/mavelli/rocker-bayesian/builds/)?

![screenshot_2018-07-05_22-08-40](https://user-images.githubusercontent.com/9298693/42356391-3867d0e8-80a0-11e8-92f5-d5c8fe602d91.png)

**Comment by mavelli** [comment]
this means the automatic build in docker hub failed - the cancelled ones are the ones i cancelled since i didnt want the build system to start building before i verified at home that it builds fine. somehow in docker hub it still fails but there are no logs to see what goes wrong. ill check asap whats going on. i guess cleaning up the Dockerfile is not what i should have done in the first place ;)

**Comment by mavelli** [comment]
short update... finally i got some log to look at from the automatic build:

```
[91mERROR: dependencies ‘dygraphs’, ‘xts’ are not available for package ‘shinystan’ [0m [91m* removing ‘/usr/local/lib/R/site-library/shinystan’ [0m [91mERROR: dependency ‘shinystan’ is not available for package ‘brms’ [0m [91m* removing ‘/usr/local/lib/R/site-library/brms’
```
seems i would need another repo mirror instead of the cloud.r-project for these... ahh

**Comment by alexhallam** [comment]
Thanks for the update. What is the alternative to the cloud.r-project?

**Comment by mavelli** [comment]
i now put a mirror hardcoded, which i know has all the packages and works fine. the Dockerfile works fine if you build it manually, however in the docker hub it still fails with "unexpected error" i opened an issue
https://github.com/docker/hub-feedback/issues/1564

for anyone wanting to build the image manually for now can use
```
docker build -t test/rocker-bayesian .
```
in a folder where the Dockerfile is saved.

**Comment by alexhallam** [comment]
how do you specify a port?
